webUrlRegex:     '(?:https://|http://|)(.+\.)?zoom\.us/(?:my|j)/(.+)'
nativeUrlFormat: 'zoommtg://$1zoom.us/join?action=join&confno=$2'
entries:
  - tool: ['gnome-screenshot', '-iac']
  - tool: ['snippingtool.exe']
